version: "3"

services:
  rate_limits_exporter:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - APP_SECRETS_DIR=/opt/secrets
      - APP_PORT=8080
      - APP_LOOP_TIME=60
      - LOG_LEVEL=DEBUG
