---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-limits-exporter
spec:
  selector:
    matchLabels:
      app: rate-limits-exporter
  template:
    metadata:
      labels:
        app: rate-limits-exporter
    spec:
      containers:
        - name: rate-limits-exporter
          image: bissquit/rate-limits-exporter:latest
          env:
            - name: APP_SECRETS_DIR
              value: "/opt/secrets/..data/"
            - name: APP_PORT
              value: "8080"
            - name: APP_LOOP_TIME
              value: "60"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: APP_PUT_SOURCE_IP
              value: "False"
          volumeMounts:
            - name: secret-volume
              mountPath: /opt/secrets/
              readOnly: true
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 40m
              memory: 128Mi
      volumes:
        - name: secret-volume
          secret:
            secretName: test-secret
