name: 'Release'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-22.04
    container: node:20-bullseye
    env:
      GITHUB_TOKEN: ${{ github.token }}
    defaults:
      run:
        shell: bash
    steps:
      - name: 'Debug'
        run: |
          printenv

      - name: 'Install and Configure applications'
        run: |
          apt-get update
          apt-get install -yqq --no-install-recommends \
            ca-certificates \
            git-core

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # fix for github hosted runners
      - name: 'Add git path to trusted'
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: 'Release'
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.0.0
          extra_plugins: |
            conventional-changelog-conventionalcommits@4.6.3
