name: 'Test chart'

on:
#  push:
  workflow_dispatch:

env:
  HELM_VERSION: v3.15.2
  KUBERNETES_CLUSTER_VERSION: v1.28.9
  KIND_VERSION: v0.23.0
  KUBE_SCORE_VERSION: v1.18.0
  CHART_NAME: rate-limits-exporter
  NAMESPACE: awesome-app

jobs:
  test-chart:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: 'Debug'
        run: |
          printenv

      - name: 'Checkout server repository'
        uses: actions/checkout@v4

      - name: 'Install prerequisites'
        run: |
          sudo apt-get update
          sudo apt-get install -yq --no-install-recommends \
            curl

          echo '--- Install Helm ---'
          curl -Lo ./helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz
          tar -zxvf helm.tar.gz
          chmod +x linux-amd64/helm
          sudo mv linux-amd64/helm /usr/local/bin/

          echo '--- Install Kubectl ---'
          curl -Lo ./kubectl https://cdn.dl.k8s.io/release/${KUBERNETES_CLUSTER_VERSION}/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

          echo '--- Install kube-score'
          curl -Lo ./kube-score.tar.gz https://github.com/zegl/kube-score/releases/download/${KUBE_SCORE_VERSION}/kube-score_${KUBE_SCORE_VERSION//v}_linux_amd64.tar.gz
          tar -zxvf kube-score.tar.gz
          chmod +x kube-score
          sudo mv kube-score /usr/local/bin/

          echo '--- Install Kind ---'
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/${KIND_VERSION}/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/

          echo '--- Create Kind cluster ---'
          kind create cluster --image kindest/node:${KUBERNETES_CLUSTER_VERSION}

      - name: 'Run Helm lint'
        run: |
          helm lint ${CHART_NAME}

      # TODO: fix all issues of kube-score
      - name: 'Run kube-score checks'
        run: |
          helm template rate-limits-exporter \
            | kube-score score \
                --ignore-test pod-networkpolicy - || true

      - name: 'Run Helm tests'
        run: |
          helm upgrade \
            --install \
            --namespace ${NAMESPACE} \
            --create-namespace \
            --values rate-limits-exporter/values-custom.yaml \
            --wait \
            rate-limits-exporter \
            ./rate-limits-exporter

          helm --namespace ${NAMESPACE} \
            test rate-limits-exporter
